<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 ./free_merc_hovercar.glb
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/free-merc-hovercar-oFfjKlslHqXgtKdKqEtpffmSv6h
Title: (FREE) Merc Hovercar
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const gltf = useGltf('3Dmodels/free_merc_hovercar.glb');
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group position={[0.02, -0.07, -0.05]} rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
			<T.Mesh geometry={gltf.nodes.Plane006_0.geometry} material={gltf.materials['Material.001']} />
			<T.Mesh geometry={gltf.nodes.Plane006_1.geometry} material={gltf.materials.Material_light} />
			<T.Mesh
				geometry={gltf.nodes.Plane_0.geometry}
				material={gltf.materials.Plane_0}
				position={[0, 0, -0.58]}
				scale={[1.19, 2, 1]}
			/>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
